CONFIG_PERF_EVENTS_INTEL_UNCORE=y
CONFIG_ACPI_AC=y
CONFIG_ACPI_BATTERY=y
CONFIG_ACPI_BUTTON=y
CONFIG_ACPI_FAN=y
CONFIG_ACPI_THERMAL=y
CONFIG_CPU_FREQ_GOV_POWERSAVE=y
CONFIG_CPU_FREQ_GOV_USERSPACE=y
CONFIG_CPU_FREQ_GOV_ONDEMAND=y
CONFIG_CPU_FREQ_GOV_CONSERVATIVE=y
CONFIG_X86_PCC_CPUFREQ=y
CONFIG_X86_ACPI_CPUFREQ=y
CONFIG_X86_POWERNOW_K8=y
CONFIG_ZSMALLOC=y
CONFIG_DNS_RESOLVER=y
CONFIG_RFKILL=y
CONFIG_EDD=y
CONFIG_CHELSIO_IPSEC_INLINE=y
CONFIG_PHYLIB=y
CONFIG_FIXED_PHY=y
CONFIG_MDIO_DEVICE=y
CONFIG_MDIO_BUS=y
CONFIG_PPP=y
CONFIG_SLHC=y
CONFIG_RTW88_8822BE=y
CONFIG_RTW88_8822CE=y
CONFIG_RTW88_8723DE=y
CONFIG_INPUT_MOUSEDEV=y
CONFIG_TOUCHSCREEN_ELAN=y
CONFIG_SERIAL_DEV_BUS=y
CONFIG_VIRTIO_CONSOLE=y
CONFIG_HW_RANDOM=y
CONFIG_I2C_CHARDEV=y
CONFIG_I2C_DESIGNWARE_CORE=y
CONFIG_I2C_DESIGNWARE_PLATFORM=y
CONFIG_PINCTRL_CHERRYVIEW=y
CONFIG_GPIO_TPS68470=y
CONFIG_PROC_THERMAL_MMIO_RAPL=y
CONFIG_WATCHDOG_PRETIMEOUT_GOV_NOOP=y
CONFIG_MFD_ARIZONA=y
CONFIG_CEC_CORE=y
CONFIG_RADIO_ADAPTERS=y
CONFIG_DRM_GEM_SHMEM_HELPER=y
CONFIG_FB_SIMPLE=y
CONFIG_USB_XHCI_PCI=y
CONFIG_MMC=y
CONFIG_VFIO=y
CONFIG_VFIO_IOMMU_TYPE1=y